### ISSUE TITLE
petpetgif on members

### ISSUE THREAD

**Issue by AceyDoCodes** [camprevail/pet-pet-gif#2]
it would be a cool feature for it to be able to get the members avatar then turn it into a petpet gif instead of just emojis

**Comment by mokurin000** [comment]
> it would be a cool feature for it to be able to get the members avatar then turn it into a petpet gif instead of just emojis

I guess this is off-topic...
Easily you can use this library in your bot

**Comment by camprevail** [comment]
Yeah this is easy to add, I just forgot about it.
